-- Migración: Agregar tablas barrios y puestos_votacion con códigos
-- Fecha: 2025-12-22

-- Crear tabla barrios
CREATE TABLE IF NOT EXISTS barrios (
  id SERIAL PRIMARY KEY,
  codigo TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Crear tabla puestos_votacion
CREATE TABLE IF NOT EXISTS puestos_votacion (
  id SERIAL PRIMARY KEY,
  codigo TEXT UNIQUE NOT NULL,
  nombre TEXT NOT NULL,
  direccion TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Crear índices para optimización
CREATE INDEX IF NOT EXISTS idx_barrios_codigo ON barrios(codigo);
CREATE INDEX IF NOT EXISTS idx_puestos_votacion_codigo ON puestos_votacion(codigo);

-- Agregar nuevos campos a tabla personas (manteniendo los antiguos temporalmente)
ALTER TABLE personas 
ADD COLUMN IF NOT EXISTS barrio_id INTEGER REFERENCES barrios(id),
ADD COLUMN IF NOT EXISTS puesto_votacion_id INTEGER REFERENCES puestos_votacion(id);

-- Crear índices para las foreign keys
CREATE INDEX IF NOT EXISTS idx_personas_barrio_id ON personas(barrio_id);
CREATE INDEX IF NOT EXISTS idx_personas_puesto_votacion_id ON personas(puesto_votacion_id);

-- Cargar datos iniciales de barrios
-- Generar códigos: BAR001, BAR002, etc.
INSERT INTO barrios (codigo, nombre) VALUES
('BAR001', 'ANTONIO NARIÑO'),
('BAR002', 'BARRIO NORMANDIA'),
('BAR003', 'BELLA MURILLO'),
('BAR004', 'COSTA DE ORO'),
('BAR005', 'EL ENCANTO'),
('BAR006', 'EL EXITO'),
('BAR007', 'ELPARQUE'),
('BAR008', 'LA ALIANZA'),
('BAR009', 'LA ARBOLEDA'),
('BAR010', 'LA FARRUCA'),
('BAR011', 'LA ILUSION'),
('BAR012', 'LA INMACULADA'),
('BAR013', 'LA PUERTA DE ORO'),
('BAR014', 'LAS COLONIAS'),
('BAR015', 'LAS COLONIAS II'),
('BAR016', 'LAS GAVIOTAS'),
('BAR017', 'LAS GAVIOTAS II'),
('BAR018', 'LAS NUBES'),
('BAR019', 'LAS TRINITARIAS'),
('BAR020', 'LOS BALKANES'),
('BAR021', 'LOS FUNDADORES'),
('BAR022', 'LOS ROSALES'),
('BAR023', 'MUVDI'),
('BAR024', 'NORMANDIA NORTE'),
('BAR025', 'NUEVA JERUSALEN'),
('BAR026', 'NUEVO MILENIO'),
('BAR027', 'PORTAL DE LAS MORAS'),
('BAR028', 'RIOS DE AGUA VIVA'),
('BAR029', 'TAJAMAR'),
('BAR030', 'TAJAMAR II'),
('BAR031', 'TERMINAL'),
('BAR032', 'URB PARQUE MUVDI'),
('BAR033', 'URB. LAS MORAS'),
('BAR034', 'VILLA CECILIA'),
('BAR035', 'VILLA DE ARAGON'),
('BAR036', 'VILLA DEL CARMEN'),
('BAR037', 'VILLA ESTEFANY'),
('BAR038', 'VILLA KATANGA'),
('BAR039', 'VILLA KATANGA II'),
('BAR040', 'VILLA LAS MORAS I'),
('BAR041', 'VILLA LINDA I'),
('BAR042', 'VILLA LOZANO'),
('BAR043', 'VILLA MERLY'),
('BAR044', 'VILLA MONACO'),
('BAR045', 'VILLA MUVDI'),
('BAR046', 'VILLA ROSA'),
('BAR047', 'VILLA SEVERA'),
('BAR048', 'VILLA SOLEDAD'),
('BAR049', 'VILLA VIOLA'),
('BAR050', 'VILLA ZAMBRANO'),
('BAR051', 'ALTOS DE LA VILLA'),
('BAR052', 'ALTOS DE LOS ALMENDROS'),
('BAR053', 'ALTOS DE LOS ROBLES'),
('BAR054', 'ALTOS DE SEVILLA'),
('BAR055', 'CIUDAD TRASNMETRO'),
('BAR056', 'CONJ RES LOS ROBLES'),
('BAR057', 'CUCHILLA DE LOS ANGELES'),
('BAR058', 'EL MANANTIAL'),
('BAR059', 'JARDIN DE VILLA ESTADIO'),
('BAR060', 'LOS ALMENDROS'),
('BAR061', 'LOS ALMENDROS II'),
('BAR062', 'LOS ALMENDROS III'),
('BAR063', 'LOS ALMENDROS IV'),
('BAR064', 'LOS CAMPANOS'),
('BAR065', 'LOS CEDROS'),
('BAR066', 'LOS CEREZOS'),
('BAR067', 'LOS ROBLES'),
('BAR068', 'LOS ROBLES IV'),
('BAR069', 'LOS ROBLES IX'),
('BAR070', 'LOS ROBLES VIII'),
('BAR071', 'LOS ROBLES X'),
('BAR072', 'MARIA DE LOS ANGELES'),
('BAR073', 'MORAS IV ETAPA'),
('BAR074', 'MORAS NORTE'),
('BAR075', 'MORAS OCCIDENTE'),
('BAR076', 'NUEVO HORIZONTE'),
('BAR077', 'NUEVO HORIZONTE II'),
('BAR078', 'PORTAL DE LOS MANANTIALES'),
('BAR079', 'PORTAL DE LOS NOGALES'),
('BAR080', 'RESERVA DE LOS ALMENDROS'),
('BAR081', 'TERRANOVA'),
('BAR082', 'TRANSMETRO'),
('BAR083', 'VILLA ANGELITA'),
('BAR084', 'VILLA CAMPANOS II'),
('BAR085', 'VILLA ESTADIO'),
('BAR086', 'VILLA ESTADIO II'),
('BAR087', 'VILLA ESTADIO NORTE'),
('BAR088', 'VILLA LAS MORAS II'),
('BAR089', 'VILLA SEVILLA'),
('BAR090', '12 DE OCTUBRE'),
('BAR091', '16 DE JUNIO'),
('BAR092', '20 DE JULIO'),
('BAR093', '7 DE AGOSTO'),
('BAR094', 'BARRIO CENTRO'),
('BAR095', 'CACHIMBERO'),
('BAR096', 'CALLE DE LAS FLORES'),
('BAR097', 'COSTA HERMOSA'),
('BAR098', 'CRUZ DE MAYO'),
('BAR099', 'EL CABRERA'),
('BAR100', 'EL CARNERO'),
('BAR101', 'EL CENTENARIO'),
('BAR102', 'EL CORTIJO'),
('BAR103', 'EL FERROCARRIL'),
('BAR104', 'EL HIPODROMO'),
('BAR105', 'EL ORIENTAL'),
('BAR106', 'EL PASITO'),
('BAR107', 'EL PORVENIR'),
('BAR108', 'EL RIO'),
('BAR109', 'EL TRIUNFO'),
('BAR110', 'EL TUCAN'),
('BAR111', 'JUAN D ROMERO'),
('BAR112', 'LA ESPERANZA'),
('BAR113', 'LA FLORESTA I'),
('BAR114', 'LA FLORESTA PLAN II'),
('BAR115', 'LA LOMA'),
('BAR116', 'LA MARIA'),
('BAR117', 'LA RIVERA'),
('BAR118', 'LA VICTORIA'),
('BAR119', 'LAS FERIAS'),
('BAR120', 'LAS MARGARITAS'),
('BAR121', 'LOS ARAYANES'),
('BAR122', 'LOS MANGOS'),
('BAR123', 'NUEVO TRIUNFO'),
('BAR124', 'PRIMERO DE MAYO'),
('BAR125', 'PUMAREJO'),
('BAR126', 'RIGOBERTA MENCHU'),
('BAR127', 'SALAMANCA'),
('BAR128', 'SALCEDO'),
('BAR129', 'SAN ANTONIO'),
('BAR130', 'SANTANA'),
('BAR131', 'SITIO HERMOSO'),
('BAR132', 'SOLUCIONES MINIMAS'),
('BAR133', 'URB. SALAMANCA'),
('BAR134', 'URB. SOL REAL'),
('BAR135', 'VILLA SALAMAR'),
('BAR136', 'VILLA SOFIA'),
('BAR137', 'VISTA HERMOSA'),
('BAR138', 'ZONA INDUSTRIAL'),
('BAR139', '23 DE NOVIEMBRE'),
('BAR140', 'AEROPUERTO'),
('BAR141', 'ALTOS DE JESUS'),
('BAR142', 'BELLA JERUSALEN'),
('BAR143', 'CIUDAD BOLIVAR'),
('BAR144', 'CIUDAD DEL PARQUE'),
('BAR145', 'CIUDAD PARAISO'),
('BAR146', 'CIUDADELA METR.'),
('BAR147', 'DOÑA MANUELA'),
('BAR148', 'EL ESFUERZO'),
('BAR149', 'EL OASIS'),
('BAR150', 'EL RECUERDO'),
('BAR151', 'GRANABASTOS'),
('BAR152', 'LA BONANZA'),
('BAR153', 'LA CANDELARIA'),
('BAR154', 'LA FE'),
('BAR155', 'LINDA MARIA'),
('BAR156', 'LINDA MARIA II'),
('BAR157', 'MANUELA BELTRAN'),
('BAR158', 'MATHA  GISELLA'),
('BAR159', 'MONTECARMELO'),
('BAR160', 'PORTAL DE S ANTONIO'),
('BAR161', 'PRADO DE SOLEDAD'),
('BAR162', 'PRADO SOLEDAD III'),
('BAR163', 'RENACER'),
('BAR164', 'SAN JUAN EUDES'),
('BAR165', 'SAN VICENTE'),
('BAR166', 'SOLEDAD DOS MIL'),
('BAR167', 'VILLA ADELA I'),
('BAR168', 'VILLA ADELA II'),
('BAR169', 'VILLA ANITA'),
('BAR170', 'VILLA DEL REY'),
('BAR171', 'VILLA ESTHER'),
('BAR172', 'VILLA GLADIS'),
('BAR173', 'VILLA MARIA'),
('BAR174', 'VILLA MONIKA'),
('BAR175', 'VILLA SOL'),
('BAR176', 'VIÑAS DEL REY'),
('BAR177', 'ZARABANDA'),
('BAR178', 'ALTOS DE LA METROPOLITANA'),
('BAR179', 'BELLO HORIZONTE'),
('BAR180', 'CIUDAD BONITA'),
('BAR181', 'CIUDAD CAMELOT'),
('BAR182', 'CIUDAD CARIBE'),
('BAR183', 'CIUDAD CARIBE IV'),
('BAR184', 'CIUDAD FALLACE'),
('BAR185', 'CIUDAD SALITRE'),
('BAR186', 'DON BOSCO'),
('BAR187', 'LA CENTRAL'),
('BAR188', 'LACANDELARIA I'),
('BAR189', 'LACANDELARIA II'),
('BAR190', 'LAS COMETAS'),
('BAR191', 'LOS CUSULES'),
('BAR192', 'LOS LOTEROS'),
('BAR193', 'NUEVA ESPERANZA'),
('BAR194', 'PORTAL DE JORDAN'),
('BAR195', 'SAN BERNARDO'),
('BAR196', 'SI NOS DEJAN'),
('BAR197', 'TERRANOVA II'),
('BAR198', 'VILLA CARMEN I'),
('BAR199', 'VILLA CARMEN II'),
('BAR200', 'VILLA KARLA I'),
('BAR201', 'VILLA MARIA SILENA'),
('BAR202', 'VILLA MURILLO'),
('BAR203', 'VILLA SANTA'),
('BAR204', 'VILLA VALENTINA')
ON CONFLICT (codigo) DO NOTHING;

-- Cargar datos iniciales de puestos de votación
-- Generar códigos: PUE001, PUE002, etc.
INSERT INTO puestos_votacion (codigo, nombre, direccion) VALUES
('PUE001', 'I.E. TECNICO LA ENSEÑANZA', 'CRA 25 No 16-69'),
('PUE002', 'I.E. INOBASOL - SEDE 2', 'CALLE 18 No. 19 - 76'),
('PUE003', 'I.E. DOLORES MA.UCROS - SEDE 3', 'CRA 20 No 15 - 14'),
('PUE004', 'I.E. INOBASOL', 'CL 15 No. 18-64'),
('PUE005', 'I.E.DOLORES MARIA UCROS', 'CARRERA 21 No. 25 - 53'),
('PUE006', 'INST. EDUCATIVA POLICARPA SALAVARRIETA', 'Cl 27 22 98'),
('PUE007', 'IE FRANCISCO DE PAULA SANTANDER', 'CRA 21 No 25 - 49'),
('PUE008', 'I.E. LUIS R CAPARROSO', 'CRA 19 NO. 25-54'),
('PUE009', 'I.E.TEC.MICROEMPRES.DE SOLEDAD', 'CARRERA 34 No. 25-45'),
('PUE010', 'I.E.SAGRADO CORAZON', 'CARRERA 36 No. 24-06'),
('PUE011', 'I.E.ANTONIO RAMON MORENO', 'CL 16 No. 29-30'),
('PUE012', 'I.E.TEC.MARIA AUXILIADORA', 'CALLE 22 No. 26 - 151'),
('PUE013', 'IE IND.DE SOLEDAD SD 2 - ITISOL', 'CRA 33 No 25-04'),
('PUE014', 'I.E.VISTA HERMOSA', 'CALLE 31 TRANSVERSAL 52 - 45'),
('PUE015', 'I.E.FCO.JOSE CALDAS - COSTA H.', 'CARRERA 40 A No. 33 -10'),
('PUE016', 'I.E. SAGRADO CORAZON S. MARGARITA', 'CALLE 24 A No.39 -17'),
('PUE017', 'COLEGIO SAGRADA SABIDURIA', 'TV 41 No. 45-237'),
('PUE018', 'I.E.INEM MIGUEL ANTONIO CARO', 'CL 30 Av. Aeropuerto'),
('PUE019', 'I.E.FRANCISCO JOSE DE CALDAS', 'CALLE 30 Av. Aeropuerto'),
('PUE020', 'I.E.NOROCCIDENTAL DE SOLEDAD', 'CALLE 55 No. 31 - 72'),
('PUE021', 'INST EDUCATIVA NOROCCIDENTAL SEDE MUVDI', 'Cl 54 24 C 1'),
('PUE022', 'I.E.TEC.I.YCOMERCIAL SEDES 1Y2', 'CALLE 60 No. 22-30'),
('PUE023', 'INSTITUTO MONSALVE NEWLOVE', 'CARRERA 19 No. 55 -93'),
('PUE024', 'COLEGIO INETECODECOL', 'Cl 67 19 35'),
('PUE025', 'LICEO SAN GABRIEL', 'CALLE 81 ENTRE CARRERA 15 Y 16'),
('PUE026', 'C.ARQUIDIOCESANO SAN PANCRACIO', 'CL 77 No. 22F-46'),
('PUE027', 'I.E.MARIA MONTESSORI', 'CARRERA 20 No. 76 - 27'),
('PUE028', 'I.E.LICEO MAYOR DE SOLEDAD', 'CRA 14 ENTRE CLL 65A Y 69A'),
('PUE029', 'IE NOBEL JUAN MANUEL SANTOS', 'CRA 6 No 78-75 B. NVA ESPERANZA'),
('PUE030', 'I.E.TEC.JOSE CASTILLO BOLIVAR', 'CARRERA 5 No. 68-43'),
('PUE031', 'CENTRO EDUCATIVO MI NUEVA GENERACION', 'CRA 7 C 77 05'),
('PUE032', 'COLEGIO LICEO NACIONAL', 'CARRERA 13 No. 59 -03'),
('PUE033', 'LICEO MIXTO SAN JOSE', 'CARRERA 11 B No. 59-60'),
('PUE034', 'INSTITUTO TECNICO EDGAR MORIN', 'CALLE 59 No. 9B - 04'),
('PUE035', 'I.E.JESUS MAESTRO F.M.S.D', 'CALLE 54 No. 8 A 03'),
('PUE036', 'COLEGIO AGUSTIN CODAZZI E U', 'CLL 56 No 10C- 115'),
('PUE037', 'CENTRO DE CAPACITACION ESPECIAL CENCAES', 'CALLE 65 NO. 8A -25'),
('PUE038', 'NUEVO COLEGIO MARIA MONTESSORI', 'CALLE 45 No. 11A - 04'),
('PUE039', 'I.E.TECNICA MANUELA BELTRAN', 'CL 38 No.10 - 09'),
('PUE040', 'I.E.NUESTRA SEÑORA DEL CARMEN', 'CARRERA 10 SUR No. 18 - 185'),
('PUE041', 'COL.METROPOLIT.DE SOLEDAD 2000', 'CRA 12A No. 51-37'),
('PUE042', 'I.E. TECNICO INDUSTRIAL EL MILAGROSO', 'CRA 13 A 1 NO. 50-35'),
('PUE043', 'INSTITUTO LUIS SANCHEZ PORTO', 'CRA 11 NO. 44-15'),
('PUE044', 'I.E.JOSEFA DONADO', 'CL 15 No. 15-82'),
('PUE045', 'IE ALBERTO PUMAREJO', 'CLL 20 No 16 - 03'),
('PUE046', 'I.E.NTRA.SRA LAS MISERICORDIAS', 'CALLE 25 No. 16 -33'),
('PUE047', 'I.E.JHON F. KENNEDY', 'CL 25 No.15 A -25'),
('PUE048', 'I.E.BICENTENARIO DE SOLEDAD', 'DIAGONAL 56 No. TR 1E - 195'),
('PUE049', 'INSTI. EDUCATIVA SAN ANTONIO DE PADUA', 'Transversal 2 D 10 55A 30'),
('PUE050', 'CDI VILLA ADELA', 'CALLE 45A #7-05'),
('PUE051', 'I.E.TAJAMAR', 'CARRERA 15B No. 45A - 03'),
('PUE052', 'I.E.CONTINENTAL DEL CARIBE', 'CALLE 53 No. 15C - 36'),
('PUE053', 'C PARA EL DES. AGROECOLO Y AGROINDUST NO', 'CRA 24 CALLE 48')
ON CONFLICT (codigo) DO NOTHING;

-- Migrar datos existentes de personas (si existen)
-- Intentar hacer match por nombre de barrio
UPDATE personas p
SET barrio_id = b.id
FROM barrios b
WHERE p.barrio IS NOT NULL 
  AND TRIM(UPPER(p.barrio)) = TRIM(UPPER(b.nombre))
  AND p.barrio_id IS NULL;

-- Intentar hacer match por nombre de puesto de votación
UPDATE personas p
SET puesto_votacion_id = pv.id
FROM puestos_votacion pv
WHERE p.puesto_votacion IS NOT NULL 
  AND TRIM(UPPER(p.puesto_votacion)) = TRIM(UPPER(pv.nombre))
  AND p.puesto_votacion_id IS NULL;

-- ============================================================================
-- RLS POLICIES PARA BARRIOS Y PUESTOS_VOTACION
-- ============================================================================

-- Habilitar Row Level Security
ALTER TABLE barrios ENABLE ROW LEVEL SECURITY;
ALTER TABLE puestos_votacion ENABLE ROW LEVEL SECURITY;

-- Políticas para barrios: todos los usuarios autenticados pueden leer
CREATE POLICY "Authenticated users can view barrios"
  ON barrios FOR SELECT
  TO authenticated
  USING (true);

-- Políticas para puestos_votacion: todos los usuarios autenticados pueden leer
CREATE POLICY "Authenticated users can view puestos_votacion"
  ON puestos_votacion FOR SELECT
  TO authenticated
  USING (true);

-- Triggers para updated_at en las nuevas tablas
CREATE TRIGGER trigger_barrios_updated_at
BEFORE UPDATE ON barrios
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();

CREATE TRIGGER trigger_puestos_votacion_updated_at
BEFORE UPDATE ON puestos_votacion
FOR EACH ROW
EXECUTE FUNCTION actualizar_updated_at();
